# Generated by Django 4.0.3 on 2022-04-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=500)),
                ('device_name', models.CharField(max_length=500)),
                ('browser_name', models.CharField(max_length=500)),
                ('last_visit', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
