# Generated by Django 4.0.3 on 2022-04-05 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_meta_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta_data',
            name='new_short_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
